/*
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moorsyl.api;

import com.moorsyl.ApiCallback;
import com.moorsyl.ApiClient;
import com.moorsyl.ApiException;
import com.moorsyl.ApiResponse;
import com.moorsyl.Configuration;
import com.moorsyl.Pair;
import com.moorsyl.ProgressRequestBody;
import com.moorsyl.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.moorsyl.model.SmsGet200Response;
import com.moorsyl.model.SmsGetRequest;
import com.moorsyl.model.SmsSend200Response;
import com.moorsyl.model.SmsSendRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SmsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SmsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SmsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for smsGet
     * @param smsGetRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call smsGetCall(SmsGetRequest smsGetRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = smsGetRequest;

        // create path and map variables
        String localVarPath = "/sms/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call smsGetValidateBeforeCall(SmsGetRequest smsGetRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'smsGetRequest' is set
        if (smsGetRequest == null) {
            throw new ApiException("Missing the required parameter 'smsGetRequest' when calling smsGet(Async)");
        }

        return smsGetCall(smsGetRequest, _callback);

    }

    /**
     * Get SMS status
     * Retrieve the current status and details of a previously sent SMS message by its ID.
     * @param smsGetRequest  (required)
     * @return SmsGet200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public SmsGet200Response smsGet(SmsGetRequest smsGetRequest) throws ApiException {
        ApiResponse<SmsGet200Response> localVarResp = smsGetWithHttpInfo(smsGetRequest);
        return localVarResp.getData();
    }

    /**
     * Get SMS status
     * Retrieve the current status and details of a previously sent SMS message by its ID.
     * @param smsGetRequest  (required)
     * @return ApiResponse&lt;SmsGet200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SmsGet200Response> smsGetWithHttpInfo(SmsGetRequest smsGetRequest) throws ApiException {
        okhttp3.Call localVarCall = smsGetValidateBeforeCall(smsGetRequest, null);
        Type localVarReturnType = new TypeToken<SmsGet200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get SMS status (asynchronously)
     * Retrieve the current status and details of a previously sent SMS message by its ID.
     * @param smsGetRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call smsGetAsync(SmsGetRequest smsGetRequest, final ApiCallback<SmsGet200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = smsGetValidateBeforeCall(smsGetRequest, _callback);
        Type localVarReturnType = new TypeToken<SmsGet200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for smsSend
     * @param smsSendRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call smsSendCall(SmsSendRequest smsSendRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = smsSendRequest;

        // create path and map variables
        String localVarPath = "/sms";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call smsSendValidateBeforeCall(SmsSendRequest smsSendRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'smsSendRequest' is set
        if (smsSendRequest == null) {
            throw new ApiException("Missing the required parameter 'smsSendRequest' when calling smsSend(Async)");
        }

        return smsSendCall(smsSendRequest, _callback);

    }

    /**
     * Send an SMS
     * Send a text message to a Mauritanian phone number. The message is queued immediately and delivered through Mauritania-optimized carrier routing.
     * @param smsSendRequest  (required)
     * @return SmsSend200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public SmsSend200Response smsSend(SmsSendRequest smsSendRequest) throws ApiException {
        ApiResponse<SmsSend200Response> localVarResp = smsSendWithHttpInfo(smsSendRequest);
        return localVarResp.getData();
    }

    /**
     * Send an SMS
     * Send a text message to a Mauritanian phone number. The message is queued immediately and delivered through Mauritania-optimized carrier routing.
     * @param smsSendRequest  (required)
     * @return ApiResponse&lt;SmsSend200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SmsSend200Response> smsSendWithHttpInfo(SmsSendRequest smsSendRequest) throws ApiException {
        okhttp3.Call localVarCall = smsSendValidateBeforeCall(smsSendRequest, null);
        Type localVarReturnType = new TypeToken<SmsSend200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Send an SMS (asynchronously)
     * Send a text message to a Mauritanian phone number. The message is queued immediately and delivered through Mauritania-optimized carrier routing.
     * @param smsSendRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call smsSendAsync(SmsSendRequest smsSendRequest, final ApiCallback<SmsSend200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = smsSendValidateBeforeCall(smsSendRequest, _callback);
        Type localVarReturnType = new TypeToken<SmsSend200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
