/*
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moorsyl.api;

import com.moorsyl.ApiCallback;
import com.moorsyl.ApiClient;
import com.moorsyl.ApiException;
import com.moorsyl.ApiResponse;
import com.moorsyl.Configuration;
import com.moorsyl.Pair;
import com.moorsyl.ProgressRequestBody;
import com.moorsyl.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.moorsyl.model.VerifyCheck200Response;
import com.moorsyl.model.VerifyCheckRequest;
import com.moorsyl.model.VerifyGet200Response;
import com.moorsyl.model.VerifySend200Response;
import com.moorsyl.model.VerifySendRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VerifyApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public VerifyApi() {
        this(Configuration.getDefaultApiClient());
    }

    public VerifyApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for verifyCheck
     * @param verifyCheckRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyCheckCall(VerifyCheckRequest verifyCheckRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = verifyCheckRequest;

        // create path and map variables
        String localVarPath = "/verify/check";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call verifyCheckValidateBeforeCall(VerifyCheckRequest verifyCheckRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'verifyCheckRequest' is set
        if (verifyCheckRequest == null) {
            throw new ApiException("Missing the required parameter 'verifyCheckRequest' when calling verifyCheck(Async)");
        }

        return verifyCheckCall(verifyCheckRequest, _callback);

    }

    /**
     * Check a verification code
     * Validate the one-time code entered by the user and return approved for a correct match, or denied when the code is incorrect, expired, or already used.
     * @param verifyCheckRequest  (required)
     * @return VerifyCheck200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public VerifyCheck200Response verifyCheck(VerifyCheckRequest verifyCheckRequest) throws ApiException {
        ApiResponse<VerifyCheck200Response> localVarResp = verifyCheckWithHttpInfo(verifyCheckRequest);
        return localVarResp.getData();
    }

    /**
     * Check a verification code
     * Validate the one-time code entered by the user and return approved for a correct match, or denied when the code is incorrect, expired, or already used.
     * @param verifyCheckRequest  (required)
     * @return ApiResponse&lt;VerifyCheck200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VerifyCheck200Response> verifyCheckWithHttpInfo(VerifyCheckRequest verifyCheckRequest) throws ApiException {
        okhttp3.Call localVarCall = verifyCheckValidateBeforeCall(verifyCheckRequest, null);
        Type localVarReturnType = new TypeToken<VerifyCheck200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Check a verification code (asynchronously)
     * Validate the one-time code entered by the user and return approved for a correct match, or denied when the code is incorrect, expired, or already used.
     * @param verifyCheckRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyCheckAsync(VerifyCheckRequest verifyCheckRequest, final ApiCallback<VerifyCheck200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = verifyCheckValidateBeforeCall(verifyCheckRequest, _callback);
        Type localVarReturnType = new TypeToken<VerifyCheck200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for verifyGet
     * @param verifySend200Response  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyGetCall(VerifySend200Response verifySend200Response, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = verifySend200Response;

        // create path and map variables
        String localVarPath = "/verify/get";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call verifyGetValidateBeforeCall(VerifySend200Response verifySend200Response, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'verifySend200Response' is set
        if (verifySend200Response == null) {
            throw new ApiException("Missing the required parameter 'verifySend200Response' when calling verifyGet(Async)");
        }

        return verifyGetCall(verifySend200Response, _callback);

    }

    /**
     * Get verification status
     * Retrieve the current status and details of a phone verification by its ID.
     * @param verifySend200Response  (required)
     * @return VerifyGet200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public VerifyGet200Response verifyGet(VerifySend200Response verifySend200Response) throws ApiException {
        ApiResponse<VerifyGet200Response> localVarResp = verifyGetWithHttpInfo(verifySend200Response);
        return localVarResp.getData();
    }

    /**
     * Get verification status
     * Retrieve the current status and details of a phone verification by its ID.
     * @param verifySend200Response  (required)
     * @return ApiResponse&lt;VerifyGet200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VerifyGet200Response> verifyGetWithHttpInfo(VerifySend200Response verifySend200Response) throws ApiException {
        okhttp3.Call localVarCall = verifyGetValidateBeforeCall(verifySend200Response, null);
        Type localVarReturnType = new TypeToken<VerifyGet200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get verification status (asynchronously)
     * Retrieve the current status and details of a phone verification by its ID.
     * @param verifySend200Response  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifyGetAsync(VerifySend200Response verifySend200Response, final ApiCallback<VerifyGet200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = verifyGetValidateBeforeCall(verifySend200Response, _callback);
        Type localVarReturnType = new TypeToken<VerifyGet200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for verifySend
     * @param verifySendRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifySendCall(VerifySendRequest verifySendRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = verifySendRequest;

        // create path and map variables
        String localVarPath = "/verify/send";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call verifySendValidateBeforeCall(VerifySendRequest verifySendRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'verifySendRequest' is set
        if (verifySendRequest == null) {
            throw new ApiException("Missing the required parameter 'verifySendRequest' when calling verifySend(Async)");
        }

        return verifySendCall(verifySendRequest, _callback);

    }

    /**
     * Send a verification code
     * Send a one-time passcode via SMS to the specified Mauritanian phone number. Returns a verificationId to use with the check endpoint.
     * @param verifySendRequest  (required)
     * @return VerifySend200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public VerifySend200Response verifySend(VerifySendRequest verifySendRequest) throws ApiException {
        ApiResponse<VerifySend200Response> localVarResp = verifySendWithHttpInfo(verifySendRequest);
        return localVarResp.getData();
    }

    /**
     * Send a verification code
     * Send a one-time passcode via SMS to the specified Mauritanian phone number. Returns a verificationId to use with the check endpoint.
     * @param verifySendRequest  (required)
     * @return ApiResponse&lt;VerifySend200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VerifySend200Response> verifySendWithHttpInfo(VerifySendRequest verifySendRequest) throws ApiException {
        okhttp3.Call localVarCall = verifySendValidateBeforeCall(verifySendRequest, null);
        Type localVarReturnType = new TypeToken<VerifySend200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Send a verification code (asynchronously)
     * Send a one-time passcode via SMS to the specified Mauritanian phone number. Returns a verificationId to use with the check endpoint.
     * @param verifySendRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call verifySendAsync(VerifySendRequest verifySendRequest, final ApiCallback<VerifySend200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = verifySendValidateBeforeCall(verifySendRequest, _callback);
        Type localVarReturnType = new TypeToken<VerifySend200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
