/*
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moorsyl.api;

import com.moorsyl.ApiException;
import com.moorsyl.model.SmsGet200Response;
import com.moorsyl.model.SmsGetRequest;
import com.moorsyl.model.SmsSend200Response;
import com.moorsyl.model.SmsSendRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SmsApi
 */
@Disabled
public class SmsApiTest {

    private final SmsApi api = new SmsApi();

    /**
     * Get SMS status
     *
     * Retrieve the current status and details of a previously sent SMS message by its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void smsGetTest() throws ApiException {
        SmsGetRequest smsGetRequest = null;
        SmsGet200Response response = api.smsGet(smsGetRequest);
        // TODO: test validations
    }

    /**
     * Send an SMS
     *
     * Send a text message to a Mauritanian phone number. The message is queued immediately and delivered through Mauritania-optimized carrier routing.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void smsSendTest() throws ApiException {
        SmsSendRequest smsSendRequest = null;
        SmsSend200Response response = api.smsSend(smsSendRequest);
        // TODO: test validations
    }

}
