/*
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moorsyl.api;

import com.moorsyl.ApiException;
import com.moorsyl.model.VerifyCheck200Response;
import com.moorsyl.model.VerifyCheckRequest;
import com.moorsyl.model.VerifyGet200Response;
import com.moorsyl.model.VerifySend200Response;
import com.moorsyl.model.VerifySendRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VerifyApi
 */
@Disabled
public class VerifyApiTest {

    private final VerifyApi api = new VerifyApi();

    /**
     * Check a verification code
     *
     * Validate the one-time code entered by the user and return approved for a correct match, or denied when the code is incorrect, expired, or already used.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyCheckTest() throws ApiException {
        VerifyCheckRequest verifyCheckRequest = null;
        VerifyCheck200Response response = api.verifyCheck(verifyCheckRequest);
        // TODO: test validations
    }

    /**
     * Get verification status
     *
     * Retrieve the current status and details of a phone verification by its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyGetTest() throws ApiException {
        VerifySend200Response verifySend200Response = null;
        VerifyGet200Response response = api.verifyGet(verifySend200Response);
        // TODO: test validations
    }

    /**
     * Send a verification code
     *
     * Send a one-time passcode via SMS to the specified Mauritanian phone number. Returns a verificationId to use with the check endpoint.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifySendTest() throws ApiException {
        VerifySendRequest verifySendRequest = null;
        VerifySend200Response response = api.verifySend(verifySendRequest);
        // TODO: test validations
    }

}
