/*
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moorsyl.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SmsSend200Response
 */
public class SmsSend200ResponseTest {
    private final SmsSend200Response model = new SmsSend200Response();

    /**
     * Model tests for SmsSend200Response
     */
    @Test
    public void testSmsSend200Response() {
        // TODO: test SmsSend200Response
    }

    /**
     * Test the property 'accepted'
     */
    @Test
    public void acceptedTest() {
        // TODO: test accepted
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    public void messageIdTest() {
        // TODO: test messageId
    }

    /**
     * Test the property 'idempotencyKey'
     */
    @Test
    public void idempotencyKeyTest() {
        // TODO: test idempotencyKey
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

}
