/*
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moorsyl.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VerifySend200Response
 */
public class VerifySend200ResponseTest {
    private final VerifySend200Response model = new VerifySend200Response();

    /**
     * Model tests for VerifySend200Response
     */
    @Test
    public void testVerifySend200Response() {
        // TODO: test VerifySend200Response
    }

    /**
     * Test the property 'verificationId'
     */
    @Test
    public void verificationIdTest() {
        // TODO: test verificationId
    }

}
